nodeChart = [
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '工商注册',
      agentName: '123',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
  ],
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '项目备案',
      agentName: '为ad',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
  ],
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '项目报建',
      agentName: '阿萨德',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
    {
      nodeName: '征地拆迁',
      agentName: '按时打算打按时打算打按时打算打按时打算打',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 2,
    },
    {
      nodeName: '土地招拍挂',
      agentName: '阿萨德',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 3,
    },
    {
      nodeName: '交地确认书',
      agentName: '皱特旗',
      createdTs: null,
      status: '跳过',
      dayNumber: null,
      sortNumber: 4,
    },
    {
      nodeName: '土地出让合同',
      agentName: null,
      createdTs: null,
      status: '进行中',
      dayNumber: 1,
      sortNumber: 5,
    },
    {
      nodeName: '建设用地规划许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 6,
    },
    {
      nodeName: '不动产权证书',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 7,
    },
    {
      nodeName: '环评审批',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 8,
    },
    {
      nodeName: '工程规划许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 9,
    },
    {
      nodeName: '施工许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 10,
    },
  ],
];

newNodeChart = [
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '工商注册',
      agentName: '123456789abcdefghijkl',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
  ],
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '项目备案',
      agentName: '为ad',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
  ],
  [
    {
      nodeName: '项目签约',
      agentName: '皱特旗',
      createdTs: '2021-07-09T00:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 0,
    },
    {
      nodeName: '项目报建',
      agentName: '按时打算打按时打算打按时打sdfsdfsdfsdfsdfsdf算打按时打算打',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 1,
    },
    {
      nodeName: '征地拆迁',
      agentName: '按时打算打按时打算打按时打sdfsdfsdfsdfsdfsdf算打按时打算打',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 2,
    },
    {
      nodeName: '土地招拍挂',
      agentName: '阿萨德',
      createdTs: '2021-07-08T16:00:00.000+0000',
      status: '完成',
      dayNumber: null,
      sortNumber: 3,
    },
    {
      nodeName: '交地确认书',
      agentName: '皱特旗',
      createdTs: null,
      status: '跳过',
      dayNumber: null,
      sortNumber: 4,
    },
    {
      nodeName: '土地出让合同',
      agentName: null,
      createdTs: null,
      status: '进行中',
      dayNumber: 1,
      sortNumber: 5,
    },
    {
      nodeName: '建设用地规划许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 6,
    },
    {
      nodeName: '不动产权证书',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 7,
    },
    {
      nodeName: '环评审批',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 8,
    },
    {
      nodeName: '工程规划许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 9,
    },
    {
      nodeName: '施工许可',
      agentName: null,
      createdTs: null,
      status: '未开始',
      dayNumber: null,
      sortNumber: 10,
    },
  ],
];
